### ISSUE TITLE
Add limits for run durations and improve run status tracking

### ISSUE THREAD

**Issue by tjwaterman99** [soupstars/api#36]
- [x] Upgrade client to end runs once a `max_duration` is exceeded
- [x] Add a max_duration field to Plan model
- [x] Add an "message" field to the run, to contain any errors that get passed
- [x] Add a "connected_at" field to the run
- [x] Improve the quality of the run status fields and support a "status" calculated field on the run:
  - X created_at ("booting instance"): inside POST /runs
  - instance_created_at ("connecting"): inside start_run job
  - connected_at ("starting"), 
  - started_at ("running"), 
  - stopped_at ("deleting instance"), 
  - deleting instance ("archiving"), 
  - archiving run ("complete")
- [x] Support a "failed or not failed" calculated field (boolean) on the run: if there's a failure on the message = "FAILED", elif archive complete = "SUCCESS", else "NONE"
- [x] Support a message associated with the failure (archiving, connecting to instance, deleting instance, etc)

On the image:
- [x] Update runner image to pass in `max_duration` when starting the run
- [x] Support setting the run.started_at from inside the instance

**Comment by tjwaterman99** [comment]
Parsers that are broken will now send a PATCH which logs the error message. The run will also be determined to have failed (`status=='failed'` and `succeeded==False`).
